VERILOG_FILES = ../src/top/zx81_blackicemx.v \
    ../src/sys/ps2.v ../src/sys/serial.v \
    ../src/sys/serreg.v ../src/sys/serperiph.v \
    ../src/fpga_zx81.v ../src/memory.v ../src/keyboard.v \
    ../src/cpu/tv80n.v ../src/cpu/tv80_core.v ../src/cpu/tv80_alu.v \
    ../src/cpu/tv80_reg.v ../src/cpu/tv80_mcode.v ../src/tristate.v

PCF_FILE = ice40hx8k.pcf

include ice40hx8kmx.mk

