#!/bin/sh

# TODO: un-hardcode path

stem=$1

org=$2

##### No $args below here!!


echo "        ;; Autogenerated!!! DONT EDIT!!!!" > ../asm/$stem.asm
echo "        org ${org}h" >> ../asm/$stem.asm
cat ../asm/$stem.template_asm >> ../asm/$stem.asm



if [ ! -f ../asm/$stem.bin ]; then
    z80-asm -c ../asm/$stem.asm $org:../asm/$stem.bin > ../asm/$stem.xref
    cp ../asm/$stem.bin ../prefab
    cp ../asm/$stem.xref ../prefab
fi

if [ ! -f ../asm/$stem.bin ]; then
    echo "z80-asm non-existing in PATH, using prefab..."
    cp ../prefab/$stem.xref ../asm
    cp ../prefab/$stem.bin ../asm
fi

