#!/bin/sh

# TODO: un-hardcode path

stem=$1

org=$2

##### No $args below here!!


echo "        ;; Autogenerated!!! DONT EDIT!!!!" > ../asm/break.asm
echo "        org ${org}h" >> ../asm/break.asm
cat ../asm/$stem.template_asm >> ../asm/break.asm

if !exists ../asm/break.bin
   z80-asm -c ../asm/break.asm $org:../asm/break.bin > ../asm/break.xref
fi

